theme = "nord"

[editor]
line-number = "relative"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1